"""admin system

Roles & account status on users, server-side sessions, append-only audit log,
security events, IP blocklist, soft delete for transactions. Existing users
become role "user" / status "active"; no data is removed.

Revision ID: 80cbb80bf587
Revises: 311a8629ac65
Create Date: 2026-10-04 17:45:50.527573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80cbb80bf587'
down_revision: Union[str, None] = '311a8629ac65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('target_user_id', sa.Uuid(), nullable=True),
    sa.Column('target_email', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor', 'audit_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_target', 'audit_logs', ['target_user_id', 'created_at'], unique=False)
    op.create_table('ip_blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('blocked_by_id', sa.Uuid(), nullable=True),
    sa.Column('blocked_by_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unblocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unblocked_by_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ip_blocks_ip_active', 'ip_blocks', ['ip_address', 'unblocked_at'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_events_created_at', 'security_events', ['created_at'], unique=False)
    op.create_index('ix_security_events_ip', 'security_events', ['ip_address', 'created_at'], unique=False)
    op.create_index('ix_security_events_type', 'security_events', ['event_type', 'created_at'], unique=False)
    op.create_index('ix_security_events_user', 'security_events', ['user_id', 'created_at'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=100), nullable=True),
    sa.Column('revoked_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['revoked_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_ip_address'), 'user_sessions', ['ip_address'], unique=False)
    op.create_index('ix_user_sessions_user_active', 'user_sessions', ['user_id', 'revoked_at'], unique=False)
    op.add_column('transactions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('deleted_by_id', sa.Uuid(), nullable=True))
    op.add_column('transactions', sa.Column('deleted_reason', sa.Text(), nullable=True))
    op.create_index('ix_transactions_created_at', 'transactions', ['created_at'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
    op.add_column('users', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('users', sa.Column('status_reason', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('status_changed_by_id', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('status_changed_by_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('registration_ip', sa.String(length=45), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_ip', sa.String(length=45), nullable=True))
    op.add_column('users', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_users_last_activity_at', 'users', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_foreign_key('fk_users_status_changed_by', 'users', 'users', ['status_changed_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "postgresql":
        # Append-only audit log: reject UPDATE and DELETE at the database level.
        op.execute(
            """
            CREATE OR REPLACE FUNCTION audit_logs_append_only() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit_logs is append-only';
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        op.execute(
            "CREATE TRIGGER audit_logs_no_change BEFORE UPDATE OR DELETE ON audit_logs "
            "FOR EACH ROW EXECUTE FUNCTION audit_logs_append_only()"
        )
        # Block Supabase's auto-generated REST API, like the other tables.
        for table in ("audit_logs", "security_events", "ip_blocks", "user_sessions"):
            op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')



def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS audit_logs_no_change ON audit_logs")
        op.execute("DROP FUNCTION IF EXISTS audit_logs_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_users_status_changed_by', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index('ix_users_last_activity_at', table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_column('users', 'last_activity_at')
    op.drop_column('users', 'last_login_ip')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'registration_ip')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'status_changed_by_email')
    op.drop_column('users', 'status_changed_by_id')
    op.drop_column('users', 'status_changed_at')
    op.drop_column('users', 'status_reason')
    op.drop_column('users', 'status')
    op.drop_column('users', 'role')
    op.drop_index('ix_transactions_created_at', table_name='transactions')
    op.drop_column('transactions', 'deleted_reason')
    op.drop_column('transactions', 'deleted_by_id')
    op.drop_column('transactions', 'deleted_at')
    op.drop_index('ix_user_sessions_user_active', table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_ip_address'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_security_events_user', table_name='security_events')
    op.drop_index('ix_security_events_type', table_name='security_events')
    op.drop_index('ix_security_events_ip', table_name='security_events')
    op.drop_index('ix_security_events_created_at', table_name='security_events')
    op.drop_table('security_events')
    op.drop_index('ix_ip_blocks_ip_active', table_name='ip_blocks')
    op.drop_table('ip_blocks')
    op.drop_index('ix_audit_logs_target', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
