"""receipt image for pending imports

Revision ID: 93a7f89230bd
Revises: 80cbb80bf587
Create Date: 2026-10-04 18:30:52.634619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a7f89230bd'
down_revision: Union[str, None] = '80cbb80bf587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_imports', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('pending_imports', sa.Column('image_content_type', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_imports', 'image_content_type')
    op.drop_column('pending_imports', 'image_data')
    # ### end Alembic commands ###
