"""add extraction method

Revision ID: 667cd0a21fec
Revises: ea15c0ba980c
Create Date: 2026-10-03 23:09:56.481840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '667cd0a21fec'
down_revision: Union[str, None] = 'ea15c0ba980c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('extraction_method', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'extraction_method')
    # ### end Alembic commands ###
